---
# tasks file for setup_speedtest_wrapper
- name: Add app user
  ansible.builtin.user:
    name: "{{ app_user }}"
    shell: /bin/bash
    system: True
  notify:
    - Restart SpeedtestWrapper service
    - Restart SpeedtestWrapper timer

- name: Service file
  ansible.builtin.template:
    src: speedtest.service
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart SpeedtestWrapper service
    - Restart SpeedtestWrapper timer

- name: Timer file
  ansible.builtin.template:
    src: speedtest.timer
    dest: "/etc/systemd/system/{{ service_name }}.timer"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Create installation folder
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Config file
  ansible.builtin.template:
    src: config.yml
    dest: "{{ install_dir }}/config.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Debug current location
  debug:
    msg: "{{ lookup('env', 'PWD') }}"

- name: Copy app binary
  ansible.builtin.copy:
    src: "{{ app_binary_path }}"
    dest: "{{ install_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0744"
