# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "debian/buster64"
  config.vm.box = "debian/buster64"


  config.vm.synced_folder ".tmp", "/app"

  config.vm.provision "shell",
    inline: "echo $(whoami)"

  config.vm.provision "shell",
    inline: "mkdir -p /app"

  config.vm.provision "file",
    source: "service/speedtest.service",
    destination: "/tmp/speedtest.service"

  config.vm.provision "file",
    source: "service/speedtest.timer",
    destination: "/tmp/speedtest.timer"

  config.vm.provision "shell",
    inline: "mv /tmp/speedtest.service /etc/systemd/system/"

  config.vm.provision "shell",
    inline: "mv /tmp/speedtest.timer /etc/systemd/system/"

  #config.vm.provision "file",
  #  source: ".tmp",
  #  destination: "/app"

  config.vm.provision "shell",
    inline: "curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash"
    
  config.vm.provision "shell",
    inline: "sudo apt-get install -y speedtest"
    
  config.vm.provision "shell",
    path: "bootstrap.sh"

end
